# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php
cache:
  apt: true
  directories:
    - node_modules

sudo: false

# WordPress version used in first build configuration.
env:
  global:
    - WP_TRAVISCI=travis:phpunit
    - WP_VERSION=4.7.3
matrix:
  include:
  - php: 7.0
  - php: 7.1
  - php: nightly
  allow_failures:
  - php: nightly

# Clones WordPress and configures our testing environment.
before_script:
    - |
      # Remove Xdebug for a huge performance increase, but not from nightly or hhvm:
      stable='^[0-9\.]+$'
      if [[ "$TRAVIS_PHP_VERSION" =~ $stable ]]; then
        phpenv config-rm xdebug.ini
      fi
    - export GIT_NAME=$(basename $(pwd))
    - export CLONED_DIR=$(pwd)
    - export PLUGIN_SLUG="avh-rps-competition"
    - |
      # Setup WordPress
      git clone git://develop.git.wordpress.org/ /tmp/wordpress
      cd /tmp/wordpress
      git checkout $WP_VERSION
    - |
      # Setup Databases
      cd /tmp/wordpress
      mysql -e "CREATE DATABASE wordpress_tests;"
      mysql -e "CREATE DATABASE rps_tests;"
      cp wp-tests-config-sample.php wp-tests-config.php
      sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
      sed -i "s/yourusernamehere/travis/" wp-tests-config.php
      sed -i "s/yourpasswordhere//" wp-tests-config.php
    - |
      # Comment out the echo as this interferes with Sessions.
      cd /tmp/wordpress
      sed -i 's/echo/\/\/echo/' tests/phpunit/includes/bootstrap.php
      sed -i 's/echo/\/\/echo/' tests/phpunit/includes/install.php
    - |
      # Setup Extra database credentials
      cd /tmp/wordpress
      echo "define( 'RPS_DB_NAME', 'rps_tests' );" >> wp-tests-config.php
      echo "define( 'RPS_DB_USER', 'travis' );" >> wp-tests-config.php
      echo "define( 'RPS_DB_PASSWORD', '' );" >> wp-tests-config.php
      echo "define( 'WP_LOCAL_DEV', false );" >> wp-tests-config.php
    - |
      # Setup AVH Framework
      git clone git://github.com/petervanderdoes/AVH-Framework.git /tmp/avh-framework
      cd /tmp/avh-framework
      git checkout develop
      mkdir -p "/tmp/wordpress/src/wp-content/mu-plugins/"
      mv "/tmp/avh-framework" "/tmp/wordpress/src/wp-content/mu-plugins/avh-framework"
      mv "/tmp/wordpress/src/wp-content/mu-plugins/avh-framework/avh-framework.php" "/tmp/wordpress/src/wp-content/mu-plugins"
    - |
      # Setup Plugin
      cd ${CLONED_DIR}/..
      mkdir -p "/tmp/wordpress/src/wp-content/plugins/"
      mv $GIT_NAME /tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG
      cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
      mkdir -p /tmp/wordpress/src/wp-content/uploads/avh-rps/framework/
    - |
      # Export Composer's global bin dir to PATH, but not on PHP 5.2:
      if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]]; then
        composer config --list --global
        export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
      fi
    - composer global require "phpunit/phpunit=5.7.*"
    - phpunit --version
script: phpunit
